DeploymenFBEvaluator syncs time
eclipse-4diac/4diac-ide pull request #200
Opened 2024-06-16 19:11 UTC by azoitl

With this change the DeploymentFBEvaluator tries to set the faketime of the evaluator device so that evaluated fbs in 4diac IDE and fbs in the device share the same time base.

2024-06-17 19:28 UTC, mx990 requested changes

2024-06-17 19:28 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.deployment.eval/src/org/eclipse/fordiac/ide/deployment/eval/fb/DeploymentFBEvaluator.java
> +			sharedState.writeDeviceParameter(FAKE_TIME_DEV_PARAM_NAME, StandardFunctions.NOW_MONOTONIC().toString());
Should we do this only if the device actually has a parameter `FakeTime`?

2024-06-20 08:51 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.deployment.eval/src/org/eclipse/fordiac/ide/deployment/eval/fb/DeploymentFBEvaluator.java
> +			sharedState.writeDeviceParameter(FAKE_TIME_DEV_PARAM_NAME, StandardFunctions.NOW_MONOTONIC().toString());
4diac FORTE as well as 4diac IDE handles this gracefully. When we finally know that this is the way to got we can still add a check but I don't see that as very important. 

@ernstblechaPT what do you think?

2024-06-20 11:03 UTC, ernstblechaPT approved these changes

2024-06-20 11:03 UTC, ernstblechaPT commented on plugins/org.eclipse.fordiac.ide.deployment.eval/src/org/eclipse/fordiac/ide/deployment/eval/fb/DeploymentFBEvaluator.java
> +			sharedState.writeDeviceParameter(FAKE_TIME_DEV_PARAM_NAME, StandardFunctions.NOW_MONOTONIC().toString());
I expect the writeVariables call to take the majority of the time, so this should for now be a negliable influence on network performance - for now I would leave this as is

2024-06-20 11:07 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.deployment.eval/src/org/eclipse/fordiac/ide/deployment/eval/fb/DeploymentFBEvaluator.java
> +			sharedState.writeDeviceParameter(FAKE_TIME_DEV_PARAM_NAME, StandardFunctions.NOW_MONOTONIC().toString());
Then I leave it as is and we will see how it behaves.

2024-06-20 11:07 UTC, merged