Added BYTES_TO_XX.fct files to utilis-1.0.0
eclipse-4diac/4diac-ide pull request #240
Opened 2024-07-01 20:35 UTC by MoritzO02

Added BYTES_TO_DWORD and BYTES_TO_WORD under the new assemblies directorie in utils-typelib
for issue #221

2024-07-02 06:36 UTC, MartinMelikMerkumians requested changes
As a general remark, TO* named functions are reserved for official cast functions.
The functions introduced here are not casts and introduce a big potential for mistyping names BYTE_TO vs BYTES_TO

Please propose other names, in order to make those functions clearly distinguishable from standardized cast functions

2024-07-02 06:36 UTC, MartinMelikMerkumians commented on data/typelibrary/utils-1.0.0/typelib/assembling/BYTES_TO_WORD.fct
> +BYTES_TO_WORD := WORD_BYTE_ZZ;
see above comment

2024-07-02 06:36 UTC, MartinMelikMerkumians commented on data/typelibrary/utils-1.0.0/typelib/assembling/BYTES_TO_DWORD.fct
> +BYTES_TO_DWORD := BYTES_TO_DWORD OR SHL(BYTE_TO_DWORD(IN_03), SHFT_BYTE_03);
The implementation can be simplified by using the bytewise access operator
e.g. `BYTES_TO_DWORD.%Bx` (or if thats not working on return values, a temporary variable)

2024-07-16 08:20 UTC, diplfranzhoepfinger commented on data/typelibrary/utils-1.0.0/typelib/assembling/ASSEMBLE_DWORD_FROM_BYTES.fct
> +(* this Function combines the 2 BYTES to a word *)
comment to the top please

2024-07-16 08:20 UTC, diplfranzhoepfinger commented on data/typelibrary/utils-1.0.0/typelib/assembling/ASSEMBLE_WORD_FROM_BYTES.fct
> +(* this Function combines the 2 BYTES to a word *)
comment to the top please.

2024-07-18 07:14 UTC, diplfranzhoepfinger approved these changes
looks good to me, Approved

2024-07-23 08:45 UTC, franz-hoepfinger-4diac approved these changes
Looks good to me, Approved.

2024-07-28 19:34 UTC, franz-hoepfinger-4diac approved these changes

2024-08-16 07:56 UTC, azoitl approved these changes

2024-08-16 07:56 UTC, merged