changed order of right click in the service sequence editor
eclipse-4diac/4diac-ide pull request #58
Opened 2024-04-16 13:43 UTC by WinterMelanie

fixed nullpointer exception when trying to create a monitorFB when there are no service sequences

Change-Id: I68f1d02c26401ea50fa0f1696b20c48053b390f1

2024-04-16 15:53 UTC, bwiesmayr requested changes

2024-04-16 15:53 UTC, bwiesmayr commented on plugins/org.eclipse.fordiac.ide.fbtypeeditor.servicesequence/src/org/eclipse/fordiac/ide/fbtypeeditor/servicesequence/handler/RecordServiceSequenceHandler.java
This looks very wrong:
 else if (cmd != null && cmd.canUndo()) {
					cmd.undo();

				}

2024-08-12 09:12 UTC, bwiesmayr commented on plugins/org.eclipse.fordiac.ide.fbtypeeditor.servicesequence/src/org/eclipse/fordiac/ide/fbtypeeditor/servicesequence/handler/RecordServiceSequenceHandler.java
I implemented undo now

2024-08-12 09:39 UTC, WinterMelanie reviewed
looks alright

2024-08-12 16:18 UTC, bwiesmayr approved these changes

2024-08-12 20:22 UTC, azoitl approved these changes

2024-08-12 20:22 UTC, merged