Draft: Implementation for LibraryElementHasher
eclipse-4diac/4diac-ide pull request #597
Opened 2024-10-07 08:46 UTC by FRoith

This change will add hashing functionality to the IDE, and automatically adds computed hash values to the output of the Forte NG exporter.

2024-10-13 14:46 UTC, azoitl requested changes
The IHasherInterface, the extension point, and the helper for getting a hasher should be moved to the model plugin, best to the typelibrary. Because we will needed it for different use cases. I would even expect that the TypeEntry will cash the hash values as they are rather expensive to create.

2024-10-13 14:46 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.export.forte_ng.st/src/org/eclipse/fordiac/ide/export/forte_ng/st/LibraryElementHasher.java
> +				parts.add(String.format("%s:%s", vdec.getName(), vdec.getTypeName())); //$NON-NLS-1$
Why are you not using your vardecl method here?

2024-10-13 14:46 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.export.forte_ng.st/src/org/eclipse/fordiac/ide/export/forte_ng/st/LibraryElementHasher.java
> +				parts.add(String.format("%s:%s", vdec.getName(), vdec.getTypeName())); //$NON-NLS-1$
Why are you not using your vardecl method here?

2024-10-13 14:46 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.export.forte_ng.st/src/org/eclipse/fordiac/ide/export/forte_ng/st/LibraryElementHasher.java
> +				parts.add(String.format("%s:%s", event.getName(), event.getTypeName())); //$NON-NLS-1$
Why are you not using your event method here?

2024-10-13 14:46 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.export.forte_ng.st/src/org/eclipse/fordiac/ide/export/forte_ng/st/LibraryElementHasher.java
> +				parts.add(String.format("%s:%s", event.getName(), event.getTypeName())); //$NON-NLS-1$
Why are you not using your event method here?

2024-10-13 14:46 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.export.forte_ng.st/src/org/eclipse/fordiac/ide/export/forte_ng/st/LibraryElementHasher.java
> +		parts.add(String.format("VDEC:%s:%s", vdec.getName(), //$NON-NLS-1$
data type name is missing

2024-10-13 14:46 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.export.forte_ng.st/src/org/eclipse/fordiac/ide/export/forte_ng/st/LibraryElementHasher.java
> +			parts.add(ecs.getName());
actions are missing

2024-10-13 19:50 UTC, mx990 commented
Aside from what @azoitl has already mentioned, I have a few general remarks regarding your current approach:

- You are hashing ST algorithms and methods by generating C++ code and using that for your hash. This means your hash:
    - is specific to the forte_ng export,
    - is sensitive to any future changes in the exported C++ code,
    - is sensitive to values of global constants in array ranges, which also makes it difficult to cache,
    - requires you to fully parse the ST code *and* generate C++ code, which makes it particularly expensive.
    
    I believe your hash is also currently sensitive to any added or removed lines in the ST code, since the generated C++ code contains `#line` directives (with the line number from the ST code). You would need to suppress them, for example, by overriding `generateLineDirective(EObject)` to return an empty string. Of course, that is easily done in this specific case, but something similar may come up again in the future and break your hash.
- You are explicitly iterating over all relevant model elements for your hash. I believe this is quite fragile and error-prone, since this makes it easy to accidentially omit relevant information. This is particularly problematic when someone else may extend the model in the future, without realising the need to extend the hash alongside it.

I would thus like to propose a different approach:
- use an XMI or binary EMF resource to generate the input for hashing,
- use the plain ST code, stripped of any extra whitespace, pragmas, and comments, for the hash,
- use meta-model annotations to specify features to be *excluded* from the hash.

I believe this has the following advantages over the current approach:
- all features are included in the hash by default,
- based on a known format instead of running our own,
- exceptions can be specified declaratively on the meta-model,
- follows any future changes to the model without significant additional work,
- does not require parsing of the ST code.

2024-10-14 19:03 UTC, azoitl commented
@mx990 how is your xmi based approach not breaking any existing XMI export?

2024-10-15 12:26 UTC, mx990 commented
> @mx990 how is your xmi based approach not breaking any existing XMI export?

I believe the hashing implementation should be entirely independent of the XMI export, although it would certainly be quite similar in how it works. I would propose the following:
- create custom annotations for the EMF meta-model [1] to:
  - exclude a feature from hashing (e.g., for comments, etc.),
  - specify a class for pre-processing elements (e.g., for ST algorithms to strip comments, etc.)
- create a custom `EcoreUtil.Copier` that:
  - skips excluded features,
  - calls the pre-processor on copied elements if specified [2],
- create a generic hasher that works similar to the XMI export [3]:
  - copy the type (with the custom `Copier`),
  - add the result into a plain `org.eclipse.emf.ecore.xmi.impl.XMIResourceImpl`,
  - save the resource into an appropriate `OutputStream`,
  - use the result for hashing.

[1] see `org.eclipse.fordiac.ide.model.emf.FordiacMetaData`
[2] see also `org.eclipse.fordiac.ide.structuredtextcore.resource.LibraryElementXtextResource.ShallowCopier`
[3] see `org.eclipse.fordiac.ide.export.xmi.XMIExportFilter`

2024-10-16 07:36 UTC, FRoith commented
I do really like the approach, I'll look into implementing it that way, and see if I hit any snags on the way. The only potential issue I see, is that I don't yet have an idea of how I would introduce detecting "old versions" of the hash with this approach, as that was one of the requested features, but I'll see what I can find.

2024-10-22 07:52 UTC, oberlehner commented
Please add unit tests.
This is really important, because we want to detect early if any implementation inside the IDE (e.g change in the parser) might potentially changes the hash values.

So please add test cases for every type that can hashed:
-SubappType
-SimpleType
-CFB
-SIFB

Are you hashing Structured Data Type ? i cannot find that in the code

2025-07-22 15:13 UTC, azoitl commented
This has been superseeded by other work.

2025-07-22 15:13 UTC, closed without merging