Fix race condition during quickfixes and repair quickfixes for configurable FBs
eclipse-4diac/4diac-ide pull request #631
Opened 2024-10-15 17:17 UTC by mx990

Fix race condition during quickfixes by refactoring marker resolutions to use proper locking of the workspace. Also combine commands for the same file and save only when necessary after applying changes. Further repair quickfixes for configurable FBs by adding validations to produce the necessary error markers.

2024-10-16 11:19 UTC, sebHollersbacher requested changes
This change breaks the option for Creating a new FB Type.
I guess by locking the workspace, the new FB type can not be created correctly

2024-10-16 13:49 UTC, mx990 commented
> This change breaks the option for Creating a new FB Type. I guess by locking the workspace, the new FB type can not be created correctly

You are right, thanks for noticing that. Should work now.

2024-10-17 11:17 UTC, sebHollersbacher approved these changes

2024-10-17 12:57 UTC, azoitl approved these changes

2024-10-17 12:57 UTC, merged