Added new EventType (EInit)
eclipse-4diac/4diac-ide pull request #667
Opened 2024-10-23 14:09 UTC by sebHollersbacher

2024-10-27 17:55 UTC, azoitl requested changes

2024-10-27 17:55 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.fbtypeeditor/src/org/eclipse/fordiac/ide/fbtypeeditor/editparts/TypeEditPart.java
>  		// allow direct edit only for VarDeclarations and AdapterDeclarations
please update the comment

2024-10-27 17:55 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.fbtypeeditor/src/org/eclipse/fordiac/ide/fbtypeeditor/editparts/TypeEditPart.java
> +		return super.isDirectEditable() && (getCastedModel() instanceof VarDeclaration
I think now the `&& ( ... )` can be removed as a whole as it covers all interface elements.

2024-10-29 09:11 UTC, oberlehner commented
![image](https://github.com/user-attachments/assets/99d6646d-e8f9-4f48-95f3-9dad7b48d660)
when an event is connected it cannot be changed.
This was an earlier feature, to prevent broken applications. But now the validation is mature enough to deal with these kind of errors, therefore please remove this check so that the event type can be changed here

2024-10-30 09:00 UTC, sebHollersbacher commented
@oberlehner Has been changed to not consider Connections

2024-11-03 22:02 UTC, azoitl commented
> @oberlehner Has been changed to not consider Connections

for me this is at least for the pin property sheet still broken.

2024-11-04 14:14 UTC, oberlehner approved these changes
Tested in UI and works fine !

2024-11-04 15:29 UTC, azoitl approved these changes

2024-11-04 15:30 UTC, merged