This commit adds varinout/data checkboxes and a new HideInOutPinCommand
eclipse-4diac/4diac-ide pull request #668
Opened 2024-10-23 14:34 UTC by PStmmr

The Property Sheet Tables for VarInouts and Data now have visible checkboxes.
New HideInOutPinCommand was also added.

2024-10-28 15:35 UTC, sebHollersbacher requested changes

2024-10-28 15:35 UTC, sebHollersbacher commented on plugins/org.eclipse.fordiac.ide.application/src/org/eclipse/fordiac/ide/application/properties/EditUntypedSubappInterfaceDataSection.java
I'm not sure if this file should change, as it has nothing to do with VarInOut's

2024-10-28 15:35 UTC, sebHollersbacher commented on plugins/org.eclipse.fordiac.ide.gef/src/org/eclipse/fordiac/ide/gef/nat/VarDeclarationColumnAccessor.java
> +	@SuppressWarnings("boxing")
This is not necessary, please remove

2024-10-28 15:35 UTC, sebHollersbacher commented on plugins/org.eclipse.fordiac.ide.gef/src/org/eclipse/fordiac/ide/gef/nat/VarDeclarationColumnAccessor.java
> +	private static VarDeclaration getPin(final VarDeclaration rowObject, final VarDeclarationTableColumn column) {
Please use a more descriptive name like 'getCorrectVarInOutPin'

2024-10-28 15:35 UTC, sebHollersbacher commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/change/HideInOutPinCommand.java
@oberlehner @azoitl Should this command inherit from HidePinCommand?

2024-10-29 09:04 UTC, oberlehner commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/change/HideInOutPinCommand.java
either it inherits from it or it uses in the command. i don't know which solution is nicer

2024-10-30 08:16 UTC, PStmmr commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/change/HideInOutPinCommand.java
Since HideInOutPinCommand doesn't implement more methods/features than HidePinCommand but just has a different type in the constructor, I decided to see HideInOutPinCommand as a separate command and as a derivative of Command.

2024-11-03 21:57 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/change/HideInOutPinCommand.java
I don't see why this command is necessary at all. Why can't you use the existing HidePinCommand?

2024-11-04 08:23 UTC, oberlehner commented on plugins/org.eclipse.fordiac.ide.gef/src/org/eclipse/fordiac/ide/gef/nat/VarDeclarationColumnAccessor.java
> +		final IInterfaceElement vD = getCorrectVarInOutPin(rowObject, column);
please name the variavle interfaceElement

vD does not make sense here

2024-11-04 08:24 UTC, oberlehner commented on plugins/org.eclipse.fordiac.ide.gef/src/org/eclipse/fordiac/ide/gef/nat/VarDeclarationColumnAccessor.java
> +		final VarDeclaration vD = getCorrectVarInOutPin(rowObject, column);
please name it VarDeclaration

2024-11-04 08:29 UTC, oberlehner commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/change/HideInOutPinCommand.java
i also see no reason for not using the existing command.
You can just create a new constructor in the HidePinCommand if you need a change to it.
The 4diac code-base is huge, so we need do not want any overhead code.

2024-11-04 08:45 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/change/HideInOutPinCommand.java
We don't even need a new constructor because no VarDeclaration specific API is used.

2024-11-04 15:13 UTC, merged