Propagate Initial value from old pin that has been renamed
eclipse-4diac/4diac-ide pull request #738
Opened 2024-11-14 08:12 UTC by oberlehner

2024-11-27 05:41 UTC, mx990 requested changes

2024-11-27 05:41 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.typemanagement/src/org/eclipse/fordiac/ide/typemanagement/refactoring/ReconnectPinChange.java
> +	FBNetworkElement element;
I believe this change is unnecessary?

2024-11-27 05:41 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.typemanagement/src/org/eclipse/fordiac/ide/typemanagement/refactoring/rename/RenameElementRefactoringProcessor.java
> +					&& eChild instanceof final IInterfaceElement varDecl) {
I suggest moving the `eChild instanceof final IInterfaceElement varDecl` out of the for loop.

2024-11-27 05:41 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.typemanagement/src/org/eclipse/fordiac/ide/typemanagement/refactoring/rename/RenameElementRefactoringProcessor.java
> +			final IInterfaceElement varDecl) {
I believe this is also used for other interface elements and not just `VarDeclaration`s? In that case, I would suggest to change the naming to reflect that.

2024-11-29 08:17 UTC, mx990 approved these changes

2024-11-29 09:59 UTC, azoitl approved these changes

2024-11-29 09:59 UTC, merged