Internal fb no type
eclipse-4diac/4diac-ide pull request #739
Opened 2024-11-14 12:13 UTC by sebHollersbacher

2024-11-14 12:31 UTC, mx990 requested changes

2024-11-14 12:31 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model/src/org/eclipse/fordiac/ide/model/dataimport/FBTImporter.java
> +			entry = addDependency(getTypeLibrary().createErrorTypeEntry(typeFbElement == null ? "" : typeFbElement, //$NON-NLS-1$
I suggest moving the null check to the beggining of https://github.com/eclipse-4diac/4diac-ide/blob/819cb6252b9688ab77d2530f7aa3333b54d770a7/plugins/org.eclipse.fordiac.ide.model/src/org/eclipse/fordiac/ide/model/typelibrary/TypeLibrary.java#L250 in order to catch all potential cases, present or future.

2024-11-18 14:20 UTC, mx990 approved these changes

2024-11-18 17:26 UTC, azoitl approved these changes

2024-11-18 17:26 UTC, merged