Draft for update infra of plant hier
eclipse-4diac/4diac-ide pull request #811
Opened 2024-12-02 12:53 UTC by oberlehner

2024-12-03 11:13 UTC, oberlehner commented
/rebase

2025-01-09 14:07 UTC, mx990 requested changes
I may have a simpler solution for handling qualified name changes in the listener:
1. collect all execute/undo/redo changes in a single list,
2. when performing the changes, first merge all changes for the same element in order.

This way, we should be able to avoid keeping a separate history for changes in addition to the command stack. What do you think?

2025-01-09 14:07 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameAffectedCommand.java
> +public abstract class QualNameAffectedCommand extends Command implements ScopedCommand {
I would suggest changing this into an interface to make it easier to add to an existing class hierarchy of commands.

2025-01-09 14:07 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameAffectedCommand.java
> +	protected abstract INamedElement getNotifier();
I would suggest renaming this to `getRenamedElement` (or something similar) to make it more clear what is being returned.

2025-01-09 14:07 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameAffectedCommand.java
> +		if (rootContainer instanceof final LibraryElement element) {
I believe having another instanceof check after an assertion makes little sense. I would suggest removing the assertion.

2025-01-09 14:07 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameChangeListener.java
> +public abstract class QualNameChangeListener {
Please extract the implementation into a separeate class and change this into an interface.

2025-01-09 14:07 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameChangeListenerManager.java
> +				e.printStackTrace();
Please properly log the exception (including the contributing plugin).

2025-01-09 14:07 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameChangeListenerManager.java
> +				if (obj instanceof QualNameChangeListener) {
Please log an error if the class is not valid (e.g., force an exception by removing the instanceof).

2025-01-09 14:07 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameChangeListenerManager.java
> +		listeners.forEach(l -> l.flush(notfier));
```suggestion
	public void removeCommandStackEventListener(final CommandStack commandStack, final Object notifier) {
		listeners.forEach(l -> l.flush(notifier));
```

2025-01-09 14:07 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameChangeListenerManager.java
> +		}
What about `POST_FLUSH` (e.g., because a reload of the editor)?

2025-01-09 14:07 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameChangeListenerManager.java
> +		final IEditorPart currentActiveEditor = EditorUtils.getCurrentActiveEditor();
I believe this does not handle the case where multiple editors are saved at once (e.g., *Save All*)? I would suggest adding a dedicated listener instance per editor to keep track of the type entry.

2025-01-09 14:07 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/change/ChangeNameCommand.java
> +		this.oldName = element.getQualifiedName();
The `oldName` is supposed to be the (unqualified) name of the element and is assigned in `execute()`.

2025-01-09 14:07 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/change/ChangeNameCommand.java
> +		return sb.toString();
```suggestion
		return getOldQualName().substring(0, getOldQualName().length() - oldName.length()) + name;
```

2025-01-09 14:07 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.hierarchymanager.ui/META-INF/MANIFEST.MF
> + org.eclipse.emf.mwe.core,
Do we actually need `org.eclipse.emf.mwe.core` as a dependency?

2025-01-14 15:05 UTC, oberlehner commented on plugins/org.eclipse.fordiac.ide.hierarchymanager.ui/META-INF/MANIFEST.MF
> + org.eclipse.emf.mwe.core,
### no

2025-01-14 15:13 UTC, oberlehner commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameAffectedCommand.java
> +public abstract class QualNameAffectedCommand extends Command implements ScopedCommand {
yes that makes sense

2025-01-14 15:18 UTC, oberlehner commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/change/ChangeNameCommand.java
> +		this.oldName = element.getQualifiedName();
you are right. i misused it

2025-01-15 08:52 UTC, oberlehner commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameAffectedCommand.java
> +	protected abstract INamedElement getNotifier();
i changed it to `getChangedElement` , i think its better then renamed, we also have the case of deletion.

2025-01-15 08:54 UTC, oberlehner commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameAffectedCommand.java
> +		if (rootContainer instanceof final LibraryElement element) {
The reason for that Assert, is that i want to know early if we get a wrong element here.
For example calling with a cached object where the eContainer can be null.

2025-01-15 08:55 UTC, oberlehner commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameChangeListener.java
> +public abstract class QualNameChangeListener {
I see no reason why i should invent another layer of abstraction.

2025-01-15 09:12 UTC, oberlehner commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameChangeListenerManager.java
> +		}
I think a postflush should also flush the pending changes ? what do you think ?

2025-01-15 09:12 UTC, oberlehner commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameChangeListenerManager.java
> +		final IEditorPart currentActiveEditor = EditorUtils.getCurrentActiveEditor();
Changed that

2025-01-15 11:10 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameAffectedCommand.java
> +		if (rootContainer instanceof final LibraryElement element) {
In that case, I would suggest replacing the second instanceof with a simple cast, since the if can only be true after the assertion.

2025-01-15 11:11 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameChangeListener.java
> +public abstract class QualNameChangeListener {
I guess we can wait until the need arises.

2025-01-15 11:18 UTC, mx990 commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameChangeListenerManager.java
> +		}
A `POST_FLUSH` should discard all pending charges, since the editor was either reloaded or closed without saving.

2025-01-16 20:06 UTC, azoitl requested changes

2025-01-16 20:06 UTC, azoitl commented on plugins/org.eclipse.fordiac.ide.model.commands/src/org/eclipse/fordiac/ide/model/commands/QualNameChangeListenerManager.java
> +	public void initialize() {
this method should be private, maybe also initializeListeners would be a better name.

2025-01-20 13:38 UTC, pazi146 approved these changes

2025-01-20 18:54 UTC, merged